name: RedundancyRemoval
on:
  push:
    branches: [ main, construction ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.9']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@latest
      with:
        version: ${{ matrix.julia-version }}
    # - name: Build Package
    #   uses: julia-actions/julia-buildpkg@latest
    - name: Test Package
      uses: julia-actions/julia-runtest@latest
    - name: Upload coverage to Codecov
      uses: julia-actions/julia-uploadcodecov@latest
      with:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Install dependencies Docs
      run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - name: Build Docs and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
        # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
      run: julia --project=docs/ docs/make.jl
